version: '2.1'

services:
  sbt:
    image: gympass/scala-sbt
    stdin_open: true
    user: user
    tty: true
    entrypoint: sbt
    environment:
      - ENV
      - ENVIRONMENT=development
      - DD_SERVICE_NAME=pet-walk-api
      - DD_WRITER_TYPE=LoggingWriter
      - PROJECT_DNS=localhost:9000
      - ELASTICSEARCH_URL=elasticsearch://elasticsearch:9200
      - RABBIT_MQ_VHOST=/
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_USERNAME=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_PORT=5672
    volumes:
      - $PWD:/app
      - m2repo:/home/user/.m2
      - ivy2:/home/user/.ivy2
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq
      - elasticsearch

  rabbitmq:
    image: rabbitmq:management

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

volumes:
  m2repo:
    external: true
  ivy2:
    external: true
